### ISSUE TITLE
Typo in the Workflow file [OS matrix field] but still works

### ISSUE THREAD

**Issue by rkzm** [githubtraining/using-github-actions-for-ci#22]
## Bug Report

**Current behavior**

Discovered a bug in the Workflow file `nodejs.yaml` code that has me wondering how the virtual environments are set up. 

The whole course works fine but observant learners will ask whats going on:

👀 at the line 

```
os: [ubuntu-lastest, windows-2016]
```
should be `-latest`

```
name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-lastest, windows-2016]
        node-version: [8.x, 10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm ci
        npm run build --if-present
        npm test
      env:
        CI: true
```

![Screen Shot 2019-11-07 at 15 04 41](https://user-images.githubusercontent.com/46698191/68361390-da188f00-0177-11ea-9392-86085c913e3b.png)

Will update these 👇 

**Reproduction**
Steps to reproduce the behavior in the course:

**Expected behavior**

**Possible solution**
If you have suggestions, we'd love to hear them. If not, that's ok too.

**Additional context**
Add any other context about the problem here. If applicable, add screenshots to help explain.
